trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sqlServerContainerName: 'sqlserver'
  sqlServerPassword: 'An9xsUzp'
  sqlServerPort: 1433

# services:
#   mssql:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     env:
#       ACCEPT_EULA: Y
#       MSSQL_SA_PASSWORD: MSSQL_SA_PASSWORD
#     ports:
#     - 1433:1433

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- script: |
    docker pull mcr.microsoft.com/mssql/server:2022-latest
  displayName: 'Pull SQL Server Linux container image'

- script: |
    docker network create mynetwork
    docker run --network mynetwork -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=$(sqlServerPassword)' -p $(sqlServerPort):1433 --name $(sqlServerContainerName) --hostname $(sqlServerContainerName) -d mcr.microsoft.com/mssql/server:2022-latest
  displayName: 'Start SQL Server Linux container'

- script: |
    docker inspect $(sqlServerContainerName)
  displayName: 'docker inspect'

- script: |
    docker network inspect mynetwork
  displayName: 'docker network inspect'

- script: |
    ping -c 4 sqlserver
  displayName: 'docker ping hostname'

# - script: |
#     docker exec $(sqlServerContainerName) hostname
#   displayName: 'docker check hostname'

# - script: |
#     docker exec $(sqlServerContainerName) /opt/mssql-tools/bin/sqlcmd -U sa -P $(sqlServerPassword) -Q "SELECT @@VERSION"
#   displayName: 'docker check sqlserver'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'MvcMovie/MvcMovie.csproj'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'MvcMovieTests/MvcMovieTests.csproj'
  displayName: 'dotnet test'

- script: |
    docker stop $(sqlServerContainerName)
    docker rm $(sqlServerContainerName)
  displayName: 'Stop and remove SQL Server Linux container'
