trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sqlServerContainerName: 'sqlserver'
  sqlServerPassword: 'An9xsUzp'
  sqlServerPort: 11433
  sqlOptions: 'Server=localhost,11433;Database=YourTestDb;User Id=sa;Password=An9xsUzp;'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - $(sqlServerPort):1433
    env:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: $(sqlServerPassword)

steps:
- script: |
    printenv | sort
  displayName: 'Print Env'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    publishTestResults: false
    projects: 'MvcMovieTests/MvcMovieTests.csproj'
    arguments: '--logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory $(System.DefaultWorkingDirectory)/MvcMovieTests/TestResults/coverage.cobertura.xml /p:CoverletOutputFormat=cobertura'
  env:
    sqlOptions: $(sqlOptions)

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/MvcMovieTests/TestResults//test-results.trx'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/MvcMovieTests/TestResults/coverage/coverage.cobertura.xml'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet build'
#   inputs:
#     command: 'build'
#     projects: 'MvcMovie/MvcMovie.csproj'
