trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sqlServerContainerName: 'sqlserver'
  sqlServerPassword: 'An9xsUzp'
  sqlServerPort: 11433
  sqlOptions: 'Server=localhost,11433;Database=YourTestDb;User Id=sa;Password=An9xsUzp;'
  coverageOutput: '$(Common.TestResultsDirectory)/TestResults/coverage/'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - $(sqlServerPort):1433
    env:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: $(sqlServerPassword)

steps:
- script: |
    printenv | sort
  displayName: 'Print Env'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'MvcMovieTests/MvcMovieTests.csproj'
    arguments: '--collect:"XPlat Code Coverage" /p:CoverletOutput=$(coverageOutput) /p:CoverletOutputFormat=cobertura'
  env:
    sqlOptions: $(sqlOptions)

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet build'
#   inputs:
#     command: 'build'
#     projects: 'MvcMovie/MvcMovie.csproj'
