trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: SA_PASSWORD
    ports:
    - 1433:1433

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.423'

- script: |
    echo "Waiting for SQL Server to be available..."
    for i in {1..30}; do
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SA_PASSWORD -Q "SELECT 1" && break
      echo "SQL Server is unavailable - sleeping"
      sleep 1
    done
    echo "SQL Server is up and running"
  displayName: 'Wait for SQL Server to be available'
  name: WaitForSqlServer

# - task: DockerInstaller@0
#   inputs:
#     dockerVersion: '17.09.0-ce'

# - script: |
#     docker pull mcr.microsoft.com/mssql/server:2022-latest
#     docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=SA_PASSWORD' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
#   displayName: 'Run SQL Server Linux container'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'MvcMovie/MvcMovie.csproj'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'MvcMovieTests/MvcMovieTests.csproj'
  displayName: 'dotnet test'

